invest/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

from core.views import choose_app

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('choose-app/', choose_app, name='choose_app'),
    path('invest_app/', include('invest_app.urls')),
    path('mortgage_app/', include('mortgage_app.urls')),
    path('intercompany_app/', include('intercompany_app.urls')),
    path('expenses_app/', include('expenses_app.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

invest_app/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'invest_app'

urlpatterns = [
    # path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('home/', views.home, name='home'),
    # path('', auth_views.LoginView.as_view(template_name='login.html'), name='login'),  # Redirect root to login
    path('add-client/', views.add_client, name='add_client'),
    path('list-clients/', views.list_clients, name='list_clients'),
    path('client/<int:client_id>/', views.client_detail, name='client_detail'),
    path('client/<int:client_id>/close_contract/', views.close_contract, name='close_contract'),
    path('show-table/', views.show_table, name='show_table'),
    path('show-google-table/', views.show_google_table, name='show_google_table'),
]

mortgage_app/urls.py
from django.urls import path
from . import views

app_name = 'mortgage_app'

urlpatterns = [
    path('home/', views.home, name='home'),
    path('loan_book/', views.loan_book, name='loan_book'),
    path('property/add/', views.add_property, name='property_add'),
    path('property/list/', views.list_property, name='property_list'),
    path('property/<str:loan_id>/', views.property_detail, name='property_detail'),
    path('property/<str:loan_id>/close_contract/', views.close_contract, name='close_contract'),
    path('property/<str:loan_id>/update_cost/', views.update_cost, name='update_cost'),
    path('fund/add/', views.add_fund, name='fund_add'),
    path('property_fund_share/add/', views.PropertyFundShareCreateView.as_view(), name='property_fund_share_add'),
    path('get_property_info/', views.get_property_info, name='get_property_info'),
    path('fund_shares', views.list_shares, name='fund_shares'),
    path('fund_shares_monthly', views.list_shares_monthly, name='fund_shares_monthly'),
    path('available_shares', views.available_shares, name='available_shares'),
    path('save-to-google-sheets/', views.save_to_google_sheets, name='save_to_google_sheets'),
    path('save-to-csv/', views.save_to_csv, name='save_to_csv'),
    path('save-to-csv-available-shares/', views.save_to_csv_available_shares, name='save_to_csv_available_shares'),
]

mortgage_app/models.py
from django.db import models


class Property(models.Model):
    loan_id = models.CharField(max_length=100)
    name = models.CharField(max_length=255)
    cost = models.DecimalField(max_digits=10, decimal_places=2)
    created = models.DateField(null=True, blank=True)
    closed = models.DateField(null=True, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Property"
        verbose_name_plural = "Properties"


class Fund(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class PropertyFundShare(models.Model):
    property = models.ForeignKey(Property, on_delete=models.CASCADE)
    fund = models.ForeignKey(Fund, on_delete=models.CASCADE)
    share_amount = models.DecimalField(max_digits=10, decimal_places=2)
    share_rate = models.DecimalField(max_digits=5, decimal_places=2)
    date_of_change = models.DateField()

    class Meta:
        unique_together = ('property', 'fund', 'date_of_change')

    def __str__(self):
        return f"{self.property.name} - {self.fund.name} - ${self.share_amount} on {self.date_of_change}"


class PropertyCostHistory(models.Model):
    property = models.ForeignKey(Property, on_delete=models.CASCADE)
    cost = models.DecimalField(max_digits=10, decimal_places=2)
    created = models.DateField(null=True, blank=True)

    def __str__(self):
        return f"{self.property.name} - ${self.cost} on {self.created}"

    class Meta:
        verbose_name = "Property cost history"
        verbose_name_plural = "Property cost histories"

mortgage_app/forms.py
from django import forms
from .models import Property, PropertyFundShare, Fund


class PropertyForm(forms.ModelForm):
    class Meta:
        model = Property
        fields = ['loan_id', 'name', 'cost']


class FundForm(forms.ModelForm):
    class Meta:
        model = Fund
        fields = ['name']


class PropertyFundShareForm(forms.ModelForm):
    class Meta:
        model = PropertyFundShare
        fields = ['property', 'fund', 'share_amount', 'share_rate', 'date_of_change']
        widgets = {
            'date_of_change': forms.DateInput(attrs={'type': 'date'})
        }

mortgage_app/views.py
import calendar
import csv
import datetime
import json

from django.contrib.auth.decorators import login_required
from django.db.models import OuterRef, Subquery, F, Max, Q
from django.db.models.functions import ExtractYear, ExtractMonth
from django.forms import model_to_dict
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST

from .dataframe import create_dataframe, update_allocations, merge_dataframes, update_spreadsheet
from .forms import PropertyForm, PropertyFundShareForm, FundForm
from .models import Property, Fund, PropertyFundShare, PropertyCostHistory


@login_required
def home(request):
    return render(request, 'mortgage_app/home.html')


@csrf_exempt
def loan_book(request):
    return render(request, 'mortgage_app/loan_book.html')


@csrf_exempt
def add_property(request):
    if request.method == 'POST':
        loan_id = request.POST.get('loan_id')
        name = request.POST.get('name')
        cost = request.POST.get('cost')
        date = request.POST.get('created')
        if not date:
            date = datetime.datetime.now()

        errors = []

        # Validate cost
        try:
            cost = float(cost)
        except ValueError:
            errors.append("Cost must be a number.")

        if errors:
            return render(request, 'mortgage_app/add_property.html', {
                'errors': errors,
                'loan_id': loan_id,
                'name': name,
                'cost': cost,
                'date': date
            })

        Property.objects.create(
            loan_id=loan_id,
            name=name,
            cost=cost,
            created=date
        )

        # Fetch the newly created Property object based on loan_id
        property_instance = Property.objects.get(loan_id=loan_id)

        # Create a PropertyCostHistory object associated with the newly created Property
        PropertyCostHistory.objects.create(
            property=property_instance,
            cost=cost,
            created=date
        )
        return render(request, 'mortgage_app/add_property.html', {
            'success': 'Property added successfully!',
            'loan_id': '',
            'name': '',
            'cost': '',
            'date': ''
        })

    return render(request, 'mortgage_app/add_property.html')


@login_required
def list_property(request):
    funds = Fund.objects.all()
    selected_fund_name = request.GET.get('fund_name')
    search_property_id = request.GET.get('search_property_id', '')

    if search_property_id:
        # Fetch properties by property ID
        properties = Property.objects.filter(loan_id__icontains=search_property_id)
    elif selected_fund_name:
        # Fetch properties associated with PropertyFundShare where fund name matches
        properties = Property.objects.filter(propertyfundshare__fund__name=selected_fund_name).order_by(
            '-loan_id').distinct()
    else:
        # Fetch all properties if no fund name or property ID is selected
        # properties = Property.objects.all().distinct('loan_id')
        # Annotate each Property with the maximum created date for its loan_id
        max_created_subquery = Property.objects.filter(
            loan_id=OuterRef('loan_id')
        ).values('loan_id').annotate(
            max_created=Max('created')
        ).values('max_created')

        # Filter the properties to keep only those with the maximum created date for their loan_id
        properties = Property.objects.annotate(
            max_created=Subquery(max_created_subquery)
        ).filter(
            created=F('max_created')
        )

    return render(request, 'mortgage_app/list_property.html', {
        'properties': properties,
        'funds': funds,
        'selected_fund_name': selected_fund_name,
        'search_property_id': search_property_id,
    })


@login_required
def property_detail(request, loan_id):
    property = get_object_or_404(Property, loan_id=loan_id)
    funds = Fund.objects.all()
    selected_fund_name = request.GET.get('fund')
    history = PropertyCostHistory.objects.filter(property=property)

    latest_date_subquery = PropertyFundShare.objects.filter(
        property=property,
        fund=OuterRef('fund')
    ).order_by('-date_of_change').values('date_of_change')[:1]

    latest_shares = PropertyFundShare.objects.filter(
        property=property,
        date_of_change=Subquery(latest_date_subquery)
    )

    available_share = property.cost - sum([share.share_amount for share in latest_shares])

    context = {
        'property': property,
        'funds': funds,
        'selected_fund_name': selected_fund_name,
        'latest_shares': latest_shares,
        'available_share': available_share,
        'current_shares': latest_shares,
        'history': history,
        # 'csrf_token': request.COOKIES['csrftoken'],
    }

    if funds:
        dataframes = []
        for fund in funds:
            # properties = Property.objects.filter(propertyfundshare__fund__name=fund.name)
            # shares = []
            # for property in properties:
            all_shares = PropertyFundShare.objects.filter(fund=fund, property=property) \
                .annotate(loan_id=F('property__loan_id')) \
                .annotate(closed=F('property__closed'))

            # shares.extend(list(all_shares))

            df = create_dataframe([property])
            update_allocations(df, list(all_shares))
            df['fund_name'] = fund.name
            dataframes.append(df)

        merged_df = merge_dataframes(dataframes)
        df_json = merged_df.to_json(index=False)
        json_data = json.loads(df_json)

        headers = list(json_data.keys())
        rows = zip(*[value.values() for value in json_data.values()])

        context['headers'] = headers
        context['rows'] = rows

        if selected_fund_name:
            fund = get_object_or_404(Fund, name=selected_fund_name)
            # properties = Property.objects.filter(propertyfundshare__fund__name=selected_fund_name)
            # shares = []
            # for property in properties:
            all_shares = PropertyFundShare.objects.filter(fund=fund, property=property) \
                .annotate(loan_id=F('property__loan_id')) \
                .annotate(closed=F('property__closed'))

            # shares.extend(list(all_shares))

            df = create_dataframe([property])
            update_allocations(df, list(all_shares))
            df.rename(columns={'loan_id': 'Loan ID', 'property_name': 'Property Name', 'cost': 'Cost'}, inplace=True)

            df_json = df.to_json(index=False)
            json_data = json.loads(df_json)

            headers = list(json_data.keys())
            rows = zip(*[value.values() for value in json_data.values()])

            context['headers'] = headers
            context['rows'] = rows
            return render(request, 'mortgage_app/property_detail.html', context)

    return render(request, 'mortgage_app/property_detail.html', context)


@csrf_exempt
def close_contract(request, loan_id):
    if request.method == 'POST':
        property = get_object_or_404(Property, loan_id=loan_id)
        close_date = request.POST.get('contract_end_date')
        date_obj = datetime.datetime.strptime(close_date, '%m/%d/%Y')
        formatted_date = date_obj.strftime('%Y-%m-%d')
        if close_date:
            # Assuming you have a field 'closed' in your Property model
            property.closed = formatted_date
            property.save()
            return JsonResponse({'status': 'success'})
        return JsonResponse({'status': 'error', 'message': 'Invalid date'}, status=400)
    return JsonResponse({'status': 'error', 'message': 'Invalid request'}, status=400)


@csrf_exempt
def update_cost(request, loan_id):
    if request.method == 'POST':
        new_cost = request.POST.get('new_cost')
        date = request.POST.get('new_cost_date')
        date_obj = datetime.datetime.strptime(date, '%m/%d/%Y')
        formatted_date = date_obj.strftime('%Y-%m-%d')
        if new_cost:
            try:
                new_cost = float(new_cost)
            except ValueError:
                return JsonResponse({'status': 'error', 'message': 'Invalid cost value.'})

            property = get_object_or_404(Property, loan_id=loan_id)
            property.cost = new_cost
            PropertyCostHistory.objects.create(property=property, cost=new_cost, created=formatted_date)
            property.save()
            return JsonResponse({'status': 'success', 'message': 'Cost updated successfully.'})
        else:
            return JsonResponse({'status': 'error', 'message': 'No cost provided.'})
    return JsonResponse({'status': 'error', 'message': 'Invalid request method.'})


@csrf_exempt
def add_fund(request):
    if request.method == 'POST':
        name = request.POST.get('name')

        errors = []

        # Validate name
        try:
            name = str(name)
        except ValueError:
            errors.append("Rate must be a string.")

        if errors:
            return render(request, 'mortgage_app/add_fund.html', {
                'errors': errors,
                'name': name,
            })

        Fund.objects.create(
            name=name,
        )

        return render(request, 'mortgage_app/add_fund.html', {
            'success': 'Fund added successfully!',
            'name': '',
        })

    return render(request, 'mortgage_app/add_fund.html')


class PropertyFundShareCreateView(View):
    def get(self, request):
        form = PropertyFundShareForm()
        return render(request, 'mortgage_app/property_fund_share_form.html', {'form': form})

    def post(self, request):
        form = PropertyFundShareForm(request.POST)
        if form.is_valid():

mortgage_app/templates/mortgage_app/home.html
<!-- /templates/mortgage_app/home.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mortgage App Home</title>
    <style>
        body {
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
            background-color: #f7f7f7;
        }
        .logo-container {
            margin-bottom: 50px; /* Adjust this value to increase/decrease space */
        }
        .button-container {
            display: flex;
            flex-direction: column;
            align-items: center;
        }
        .button-container button {
            margin: 10px;
            padding: 15px 30px;
            font-size: 16px;
            border: none;
            border-radius: 5px;
            background-color: #006dd1;
            color: white;
            cursor: pointer;
            transition: background-color 0.3s;
            width: 200px;
        }
        .button-container button:hover {
            background-color: #0056b3;
        }
        .button-container .choose-app {
            background-color: #006400;
        }
        .button-container .choose-app:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
    <!-- Include the static files in the template -->
    <div class="logo-container">
        {% load static %}
        <img src="{% static 'images/faes_co_logo.png' %}" alt="Logo" style="width: 200px; height: auto;">
    </div>
    <div class="button-container">
        <button onclick="location.href='{% url 'mortgage_app:loan_book' %}'">Loan Book</button>
<!--        <button onclick="location.href='{% url 'invest_app:list_clients' %}'">List Clients</button>-->
<!--        <button onclick="location.href='{% url 'invest_app:show_table' %}'">Investments Data</button>-->
<!--        <button onclick="location.href='{% url 'invest_app:show_google_table' %}'">Google Sheets</button>-->
        <button class="choose-app" onclick="location.href='{% url 'choose_app' %}'">Change App</button>
    </div>
</body>
</html>

mortgage_app/templates/mortgage_app/loan_book.html
<!-- /templates/mortgage_app/home.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mortgage App Home</title>
    <style>
        body {
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
            background-color: #f7f7f7;
        }
        .logo-container {
            margin-bottom: 50px; /* Adjust this value to increase/decrease space */
        }
        .button-container {
            display: flex;
            flex-direction: column;
            align-items: center;
        }
        .button-container button {
            margin: 5px;
            padding: 15px 30px;
            font-size: 16px;
            border: none;
            border-radius: 5px;
            background-color: #006dd1;
            color: white;
            cursor: pointer;
            transition: background-color 0.3s;
            width: 200px;
        }
        .button-container button:hover {
            background-color: #0056b3;
        }
        .button-container .property-button,
        .button-container .shares-button,
        .button-container .monthly-shares-button {
            background-color: #28a745;
        }
        .button-container .property-button:hover,
        .button-container .shares-button:hover,
        .button-container .monthly-shares-button:hover {
            background-color: #218838;
        }
<!--        .button-container .shares-button {-->
<!--            background-color: #28a745;-->
<!--        }-->
<!--        .button-container .shares-button:hover {-->
<!--            background-color: #218838;-->
<!--        }-->
        .button-container .choose-app {
            background-color: #006400;
        }
        .button-container .choose-app:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
    <!-- Include the static files in the template -->
    <div class="logo-container">
        {% load static %}
        <img src="{% static 'images/faes_co_logo.png' %}" alt="Logo" style="width: 200px; height: auto;">
    </div>
    <div class="button-container">
        <button onclick="location.href='{% url 'mortgage_app:property_add' %}'">Add Property</button>
        <button onclick="location.href='{% url 'mortgage_app:fund_add' %}'">Add fund</button>
        <button onclick="location.href='{% url 'mortgage_app:property_fund_share_add' %}'">Add fund share</button>
        <button class="property-button" onclick="location.href='{% url 'mortgage_app:property_list' %}'">List Property</button>
        <button class="shares-button" onclick="location.href='{% url 'mortgage_app:fund_shares' %}'">List Shares</button>
        <button class="shares-button" onclick="location.href='{% url 'mortgage_app:fund_shares_monthly' %}'">List Shares Monthly</button>
        <button class="shares-button" onclick="location.href='{% url 'mortgage_app:available_shares' %}'">List Available Shares</button>
        <button class="back-button" onclick="location.href='{% url 'mortgage_app:home' %}'">Back to Home</button>
        <button class="choose-app" onclick="location.href='{% url 'choose_app' %}'">Change App</button>
    </div>
</body>
</html>

mortgage_app/templates/mortgage_app/property_fund_share_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Allocate funds</title>
    <style>
        body {
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            min-height: 100vh;
            margin: 0;
            background-color: #f7f7f7;
            font-family: Arial, sans-serif;
        }
        .form-container {
            display: flex;
            justify-content: center;
            align-items: flex-start;
            max-width: 1000px;
            width: 100%;
            margin-top: 20px;
        }
        form {
            width: 300px;
        }
        form p {
            margin-bottom: 15px;
        }
        form input, form select, form textarea {
            width: 100%;
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 4px;
            box-sizing: border-box;
        }
        button[type="submit"] {
            width: 100%;
            padding: 10px;
            background-color: #006dd1;
            color: white;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            font-size: 16px;
            box-sizing: border-box;
            margin-top: 10px;
        }
        button[type="submit"]:hover {
            background-color: #0056b3;
        }
        #additional-info {
            width: 300px;
            margin-top: 30px;
            padding: 10px;
            background-color: #eaeaea;
            border: 1px solid #ccc;
            border-radius: 4px;
            margin-left: 20px;
            transition: transform 0.3s ease-out;
            transform: translateX(-100%);
            opacity: 0;
            display: none;
        }
        #additional-info.visible {
            transform: translateX(0);
            opacity: 1;
            display: block;
        }
        .button-container {
            display: flex;
            justify-content: center;
            margin-top: 20px;
            width: 100%;
        }
        .button-container button {
            padding: 10px 30px;
            font-size: 16px;
            border: none;
            border-radius: 5px;
            background-color: #006dd1;
            color: white;
            cursor: pointer;
            transition: background-color 0.3s;
        }
        .button-container button:hover {
            background-color: #0056b3;
        }
        .success {
            color: green;
            font-size: 14px;
            margin-bottom: 20px;
        }
    </style>
</head>
<body>
    <h1>Allocate funds</h1>
    {% if success %}
        <div class="success">{{ success }}</div>
    {% endif %}
    <div class="form-container">
        <form method="post" id="allocation-form">
            {% csrf_token %}
            {{ form.as_p }}
            <div id="share-amount-warning" style="color: red; display: none;"></div>
            <div id="date-warning" style="color: red; display: none;"></div>
            <button type="submit">Save</button>
        </form>
        <div id="additional-info">
            <!-- Content for additional info goes here -->
        </div>
    </div>
    <div class="button-container">
        <button class="back-button" onclick="location.href='{% url 'mortgage_app:loan_book' %}'">Back to Loan Book</button>
    </div>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
        $(document).ready(function() {
            var getPropertyInfoUrl = "{% url 'mortgage_app:get_property_info' %}";
            var availableShare = 0;
            var propertyCreationDate = null;

            // Function to filter and display only open properties
            function updatePropertyOptions() {
                var propertySelect = $('#id_property');
                propertySelect.find('option').each(function() {
                    var propertyId = $(this).val();
                    if (propertyId) {
                        $.ajax({
                            url: getPropertyInfoUrl,
                            data: { 'property_id': propertyId },
                            dataType: 'json',
                            async: false,  // Make this synchronous to ensure proper ordering
                            success: function(data) {
                                if (data.closed) {
                                    $(this).hide();
                                } else {
                                    $(this).show();
                                }
                            }.bind(this),
                            error: function(xhr, status, error) {
                                console.error('Error fetching property info:', error);
                            }
                        });
                    }
                });
            }

            // Call this function when the page loads
            updatePropertyOptions();

            $('#id_property').change(function() {
                var propertyId = $(this).val();
                if (propertyId) {
                    $.ajax({
                        url: getPropertyInfoUrl,
                        data: { 'property_id': propertyId },
                        dataType: 'json',
                        success: function(data) {
                            if (data.closed) {
                                alert("This property is closed and cannot be selected.");
                                $('#id_property').val('');  // Reset selection
                                $('#additional-info').removeClass('visible').empty();
                                return;
                            }

                            var additionalInfoHtml = '<p><strong>Address:</strong> ' + data.name + '</p>';
                            additionalInfoHtml += '<p><strong>Loan ID:</strong> ' + data.loan_id + '</p>';
                            additionalInfoHtml += '<p><strong>Available Share:</strong> ' + data.available_share + '</p>';
                            additionalInfoHtml += '<p><strong>Latest Shares:</strong></p>';
                            data.latest_shares.forEach(function(share) {
                                var dateObj = new Date(share.date);
                                var formattedDate = dateObj.toLocaleDateString();
                                additionalInfoHtml += '<p>' + share.fund_name + ' ' + share.share_amount + ' ' + formattedDate + '</p>';
                            });
                            additionalInfoHtml += '</p>';
                            $('#additional-info').html(additionalInfoHtml).addClass('visible');

                            availableShare = parseFloat(data.available_share);
                            propertyCreationDate = new Date(data.created);

                            $('#id_share_amount').on('input', function() {
                                var shareAmount = parseFloat($(this).val());
                                var warningElement = $('#share-amount-warning');

                                if (isNaN(shareAmount) || shareAmount <= availableShare) {
                                    warningElement.hide();
                                } else {
                                    warningElement.text('Warning: The share amount exceeds the available share.').show();
                                }
                            });

                            $('#allocation-form').off('submit').submit(function(e) {
                                var shareAmount = parseFloat($('#id_share_amount').val());
                                var formDate = new Date($('#id_date_of_change').val());
                                var dateWarningElement = $('#date-warning');

<!--                                if (shareAmount > availableShare) {-->
<!--                                    e.preventDefault();-->
<!--                                    alert('The share amount exceeds the available share. Please adjust the amount.');-->
<!--                                }-->

                                if (propertyCreationDate && formDate < propertyCreationDate) {
                                    e.preventDefault();
                                    dateWarningElement.text('The allocation date cannot be before the property creation date.').show();
                                    alert('The allocation date cannot be before the property creation date. Please adjust the date.');
                                }
                            });
                        },
                        error: function(xhr, status, error) {
                            console.error('Error fetching property info:', error);
                        }
                    });
                } else {
                    $('#additional-info').removeClass('visible').empty();
                    availableShare = 0;
                    propertyCreationDate = null;
                    $('#share-amount-warning').hide();
                    $('#date-warning').hide();

                    $('#id_share_amount').off('input');
                    $('#allocation-form').off('submit');
                }
            });
        });
    </script>
</body>
</html>