expenses_app/urls.py
from django.urls import path
from expenses_app import views

app_name = 'expenses_app'

urlpatterns = [
    path('home/', views.home, name='home'),
    path('add-invoice/', views.add_invoice, name='add_invoice'),
    path('list-invoice/', views.list_invoices, name='list_invoices'),
    path('save-to-google-sheets/', views.push_to_google_table, name='save_to_google_sheets'),
]

intercompany_app/urls.py
from django.urls import path

from intercompany_app import views

app_name = 'intercompany_app'

urlpatterns = [
    path('home/', views.home, name='home'),
    path('add_table/', views.add_table, name='add_table'),
    path('view_table/', views.view_table, name='view_table'),
    path('add_transaction/', views.add_transaction, name='add_transaction'),
    path('edit_finished_date/', views.edit_finished_date, name='edit_finished_date'),
    path('save_to_google_sheets/', views.push_to_google_table, name="save_to_google_sheets"),
    path('update_google_sheets/', views.update_sheet, name="update_google_sheets")
]

invest/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

from core.views import choose_app

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('choose-app/', choose_app, name='choose_app'),
    path('invest_app/', include('invest_app.urls')),
    path('mortgage_app/', include('mortgage_app.urls')),
    path('intercompany_app/', include('intercompany_app.urls')),
    path('expenses_app/', include('expenses_app.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

invest_app/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'invest_app'

urlpatterns = [
    # path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('home/', views.home, name='home'),
    # path('', auth_views.LoginView.as_view(template_name='login.html'), name='login'),  # Redirect root to login
    path('add-client/', views.add_client, name='add_client'),
    path('list-clients/', views.list_clients, name='list_clients'),
    path('client/<int:client_id>/', views.client_detail, name='client_detail'),
    path('client/<int:client_id>/close_contract/', views.close_contract, name='close_contract'),
    path('show-table/', views.show_table, name='show_table'),
    path('show-google-table/', views.show_google_table, name='show_google_table'),
]

mortgage_app/urls.py
from django.urls import path
from . import views

app_name = 'mortgage_app'

urlpatterns = [
    path('home/', views.home, name='home'),
    path('loan_book/', views.loan_book, name='loan_book'),
    path('property/add/', views.add_property, name='property_add'),
    path('property/list/', views.list_property, name='property_list'),
    path('property/<str:loan_id>/', views.property_detail, name='property_detail'),
    path('property/<str:loan_id>/close_contract/', views.close_contract, name='close_contract'),
    path('property/<str:loan_id>/update_cost/', views.update_cost, name='update_cost'),
    path('fund/add/', views.add_fund, name='fund_add'),
    path('property_fund_share/add/', views.PropertyFundShareCreateView.as_view(), name='property_fund_share_add'),
    path('get_property_info/', views.get_property_info, name='get_property_info'),
    path('fund_shares', views.list_shares, name='fund_shares'),
    path('fund_shares_monthly', views.list_shares_monthly, name='fund_shares_monthly'),
    path('available_shares', views.available_shares, name='available_shares'),
    path('save-to-google-sheets/', views.save_to_google_sheets, name='save_to_google_sheets'),
    path('save-to-csv/', views.save_to_csv, name='save_to_csv'),
    path('save-to-csv-available-shares/', views.save_to_csv_available_shares, name='save_to_csv_available_shares'),
]

core/models.py
from django.db import models

# Create your models here.

core/views.py
# core/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required


@login_required
def choose_app(request):
    return render(request, 'core/choose_app.html')

core/templates/core/choose_app.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Anton+SC&family=Roboto+Mono:ital,wght@0,100..700;1,100..700&family=Ubuntu:ital,wght@0,300;0,400;0,500;0,700;1,300;1,400;1,500;1,700&display=swap" rel="stylesheet">
    <title>Choose App</title>
    <style>
        body {
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
            background-color: #f7f7f7;
        }
        .logo-container {
            margin-bottom: 50px; /* Adjust this value to increase/decrease space */
        }
        .container {
            text-align: center;
        }
        .buttons {
            display: flex;
            justify-content: center;
            gap: 20px;
        }
        .buttons a {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 60px; /* Set desired height */
            margin: 5px;
            font-size: 24px;
            text-decoration: none;
            color: #fff;
            background-color: #006400;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            width: 200px;
            font-family: "Ubuntu", sans-serif;
            font-weight: 700;
            font-style: normal;
        }
        .buttons a:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
    <div class="logo-container">
        {% load static %}
        <img src="{% static 'images/faes_co_logo.png' %}" alt="Logo" style="width: 200px; height: auto;">
    </div>
    <div class="container">
        <div class="buttons">
            <a href="{% url 'invest_app:home' %}">Invest App</a>
            <a href="{% url 'mortgage_app:home' %}">Mortgage App</a>
            <a href="{% url 'intercompany_app:home' %}">InterCompany App</a>
            <a href="{% url 'expenses_app:home' %}">Prepaid Expenses App</a>
        </div>
    </div>
</body>
</html>