expenses_app/urls.py
from django.urls import path
from expenses_app import views

app_name = 'expenses_app'

urlpatterns = [
    path('home/', views.home, name='home'),
    path('add-invoice/', views.add_invoice, name='add_invoice'),
    path('list-invoice/', views.list_invoices, name='list_invoices'),
    path('save-to-google-sheets/', views.push_to_google_table, name='save_to_google_sheets'),
]

invest/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

from core.views import choose_app

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('choose-app/', choose_app, name='choose_app'),
    path('invest_app/', include('invest_app.urls')),
    path('mortgage_app/', include('mortgage_app.urls')),
    path('intercompany_app/', include('intercompany_app.urls')),
    path('expenses_app/', include('expenses_app.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

expenses_app/models.py
from django.db import models

# Entity model
class Entity(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


# Invoice model
class Invoice(models.Model):

    entity = models.ForeignKey(Entity, on_delete=models.CASCADE, related_name='invoices')
    vendor_name = models.CharField(max_length=100)
    invoice_number = models.CharField(max_length=50, unique=True)
    invoice_date = models.DateField()
    invoice_file = models.FileField(upload_to='invoices/', blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    expense_name = models.CharField(max_length=100)
    dt_account = models.CharField(max_length=100)
    cr_account = models.CharField(max_length=100)
    invoice_amount = models.DecimalField(max_digits=15, decimal_places=2)
    number_of_months = models.PositiveIntegerField(default=1)

    def __str__(self):
        return f"Invoice {self.invoice_number} - {self.vendor_name}"

expenses_app/forms.py
from django import forms
from .models import Invoice

class InvoiceForm(forms.ModelForm):
    class Meta:
        model = Invoice
        fields = [
            'entity',
            'vendor_name',
            'invoice_number',
            'invoice_date',
            'invoice_file',
            'description',
            'expense_name',
            'dt_account',
            'cr_account',
            'invoice_amount',
            'number_of_months'
        ]
        widgets = {
            'invoice_date': forms.DateInput(attrs={'type': 'date'}),
            'description': forms.Textarea(attrs={'rows': 3}),
        }
        labels = {
            'entity': 'Entity Name',
            'invoice_number': 'Invoice #',
            'dt_account': 'Dt Account',
            'cr_account': 'Cr Account',
        }

        invoice_file = forms.FileField(required=False)

expenses_app/views.py
import json

from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt

from . import google_sheet
from .forms import InvoiceForm
from .models import Invoice


@login_required
def home(request):
    return render(request, 'expenses_app/home.html')

@csrf_exempt
def add_invoice(request):
    if request.method == 'POST':
        form = InvoiceForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            # Save or process form data
            return redirect('expenses_app:add_invoice')
    else:
        form = InvoiceForm()

    return render(request, 'expenses_app/add_invoice.html', {'form': form})

@login_required
def list_invoices(request):
    invoices = Invoice.objects.all().order_by('invoice_date')

    headers, rows = google_sheet.build_table(invoices)

    # Pass the data to the template
    return render(request, 'expenses_app/list_invoices.html',
                  {'headers': headers,
                   'rows': rows})

@login_required()
def push_to_google_table(request):
    data = json.loads(request.body)
    if data.get('update', False):
        invoices = Invoice.objects.all().order_by('invoice_date')
        try:
            google_sheet.update_spreadsheet(invoices)
            return JsonResponse({'success': True})
        except Exception as e:
            return JsonResponse({'success': False, 'error': str(e)})

expenses_app/templates/expenses_app/add_invoice.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add Invoice</title>
    <style>
        body {
            display: flex;
            flex-direction: column;
            justify-content: flex-start;
            align-items: center;
            height: 100vh;
            margin: 0;
            background-color: #f7f7f7;
        }
        form {
            display: flex;
            flex-direction: column;
        }
        form p {
            margin-bottom: 15px;
        }
        form input, form select, form textarea {
            width: 100%;
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 4px;
        }
        button[type="submit"] {
            width: 100%;
            padding: 10px;
            background-color: #0056b3;
            color: white;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            font-size: 16px;
        }
        button[type="submit"]:hover {
            background-color: #6c757d;
        }
        .button-container {
            display: flex;
            flex-direction: column;
            align-items: center;
        }
        .button-container button {
            margin: 10px;
            padding: 15px 30px;
            font-size: 16px;
            border: none;
            border-radius: 5px;
            background-color: #006dd1;
            color: white;
            cursor: pointer;
            transition: background-color 0.3s;
            width: 200px;
        }
        .button-container button:hover {
            background-color: #0056b3;
        }
        .back-button {
            margin-top: 20px;
            padding: 10px;
            font-size: 16px;
            border: none;
            border-radius: 5px;
            background-color: #0056b3;
            color: white;
            cursor: pointer;
            transition: background-color 0.3s;
        }
        .back-button:hover {
            background-color: #6c757d;
        }
    </style>
</head>
<body>
    <h2>Add New Invoice</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
        <button class="back-button" onclick="location.href='{% url 'expenses_app:home' %}'">Back Home</button>
    </form>
</body>
</html>

expenses_app/templates/expenses_app/home.html
<!-- /templates/expenses_app/home.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Prepaid expenses App Home</title>
    <style>
        body {
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
            background-color: #f7f7f7;
        }
        .logo-container {
            margin-bottom: 50px; /* Adjust this value to increase/decrease space */
        }
        .button-container {
            display: flex;
            flex-direction: column;
            align-items: center;
        }
        .button-container button {
            margin: 10px;
            padding: 15px 30px;
            font-size: 16px;
            border: none;
            border-radius: 5px;
            background-color: #006dd1;
            color: white;
            cursor: pointer;
            transition: background-color 0.3s;
            width: 200px;
        }
        .button-container button:hover {
            background-color: #0056b3;
        }

        .button-container .save-button {
            background-color: #38761d;
        }
        .save-button:hover {
            background-color: #45a049;
        }
        .button-container .choose-app {
            background-color: #006400;
        }
        .button-container .choose-app:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
    <div class="logo-container">
        {% load static %}
        <img src="{% static 'images/faes_co_logo.png' %}" alt="Logo" style="width: 200px; height: auto;">
    </div>
    <div class="button-container">
        <button onclick="location.href='{% url 'expenses_app:add_invoice' %}'">Add Invoice</button>
        <button onclick="location.href='{% url 'expenses_app:list_invoices' %}'">List Invoices</button>
<!--        <button id="saveToGoogleSheets" class="save-button">Save to Google Sheets</button>-->
        <button class="choose-app" onclick="location.href='{% url 'choose_app' %}'">Change App</button>
    </div>
</body>
</html>

expenses_app/templates/expenses_app/list_invoices.html
<!-- templates/expenses_app/list_invoices.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Invoice List</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f7f7f7;
            margin: 0;
            padding: 20px;
            box-sizing: border-box;
            max-width: 100%;
            overflow-x: hidden;
        }
        .container {
            max-width: 100%;
            margin: 0 auto;
            padding: 0 15px;
        }
        .table_entries {
            background-color: #fff;
            border-radius: 5px;
            box-shadow: 0 0 10px rgba(0,0,0,0.1);
            padding: 20px;
            margin-bottom: 20px;
        }
        .table-container {
            position: relative;
            width: 100%;
            overflow-x: auto;
            max-height: 500px;
            overflow-y: auto;
        }
        table {
            border-collapse: separate;
            border-spacing: 0;
            width: 100%;
        }
        th, td {
            padding: 12px;
            border: 1px solid #ddd;
            text-align: center;
            white-space: nowrap;
        }
        th {
            background-color: #f2f2f2;
            position: sticky;
            top: 0;
            z-index: 2;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        tr:hover {
            background-color: #f1f1f1;
        }

        /* Freeze first 3 columns */
        th:nth-child(-n+2),
        td:nth-child(-n+2) {
            position: sticky;
            background-color: #fff; /* Ensure background-color to overlap other columns */
            z-index: 1;
        }

        th:nth-child(1), td:nth-child(1) {
            left: 0;
            z-index: 2; /* Ensure higher z-index */
            width: 120;
        }
        th:nth-child(2), td:nth-child(2) {
            left: 118px; /* Adjust based on the width of the first column */
            z-index: 3; /* Ensure higher z-index */
        }

        /* Ensure frozen column headers are on top of everything */
        th:nth-child(-n+2) {
            z-index: 5;
        }

        /* Add box-shadow to create a separation effect */
        th:nth-child(2) {
            box-shadow: 2px 0 5px -2px rgba(0,0,0,0.3);
        }

        .button-container {
            margin-bottom: 20px;
        }

        .back-button, .close-contract-button, .save-button {
            margin-top: 20px;
            padding: 10px;
            font-size: 16px;
            border: none;
            border-radius: 5px;
            background-color: #006dd1;
            color: white;
            cursor: pointer;
            transition: background-color 0.3s;
        }
        .back-button:hover, .close-contract-button:hover, .save-button:hover {
            background-color: #0056b3;
        }

    </style>
</head>
<body>
    <h1>Invoice List</h1>
    <div class="button-container">
        <button id="saveToGoogleSheets" class="save-button">Save to Google Sheets</button>
    </div>
    <!-- Table to display invoices -->
    <div class="table-container">
    <table border="1">
    <thead>
        <tr>
            {% for header in headers %}
                <th>{{ header }}</th>
            {% endfor %}
        </tr>
    </thead>
    <tbody>
        {% if rows %}
            {% for row in rows %}
                <tr>
                    {% for cell in row %}
                        <td>
                            {% if forloop.counter == 3 and cell.url %}
                                <a href="{{ cell.url }}" target="_blank">{{ cell.text }}</a>
                            {% elif forloop.counter == 3 and not cell.url %}
                                {{ cell.text }}
                            {% else %}
                                {{ cell }}
                            {% endif %}
                        </td>
                    {% endfor %}
                </tr>
            {% endfor %}
        {% else %}
            <tr>
                <td colspan="{{ headers|length }}">No invoices found.</td>
            </tr>
        {% endif %}
    </tbody>
    </table>
    </div>
    <button class="back-button" onclick="location.href='{% url 'expenses_app:home' %}'">Back Home</button>
    <script>
        document.getElementById('saveToGoogleSheets').addEventListener('click', function() {
            fetch('{% url "expenses_app:save_to_google_sheets" %}', {
                method: 'POST',
                headers: {
                    'X-CSRFToken': '{{ csrf_token }}',
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify({
                    update: true
                })
            })
            .then(response => response.json())
            .then(data => {
                if (data.success) {
                    alert('Data saved to Google Sheets successfully!');
                } else {
                    alert('Error saving data to Google Sheets: ' + (data.error || 'Unknown error'));
                }
            })
            .catch(error => {
                console.error('Error:', error);
                alert('An error occurred while saving data to Google Sheets.');
            });
        });
    </script>
</body>
</html>